version: '3.8'
services:
  pgsync:
    network_mode: host
    build:
      dockerfile: docker/dev.Dockerfile
      context: .
    volumes:
      - ./dist:/dist
      - ./src:/src
      - ./config.yaml:/app/config.yaml
    command:
      - ash
      - -c
      - "sleep infinity"
    restart: always

  prod:
    network_mode: host
    build:
      dockerfile: docker/prod.Dockerfile
      context: .
    volumes:
      - ./config.yaml:/app/config.yaml
    restart: always