version: '3.8'
services:
  #    cache:
  #        image: redis
  #        container_name: cache
  #        ports:
  #            - 6379:${REDIS_PORT}
  #        volumes:
  #            - ./storage/redis:/data
  #        command: redis-server --requirepass ${REDIS_PASS} --appendonly yes
  pgsync:
    network_mode: host
    build: '.'
    #        container_name: api
    #        links:
    #            - cache
    #        depends_on:
    #            - cache
    #            - db
    #        ports:
    #            - 8080:${PORT}
    volumes:
      - ./dist:/dist
      - ./src:/src
      - ./config.yaml:/src/config.yaml
    #        environment:
    #            PORT: ${PORT}
    #            MODE: ${MODE}
    #            DB_USER: ${DB_USER}
    #            DB_PASS: ${DB_PASS}
    #            DB_NAME: ${DB_NAME}
    #            DB_HOST: ${DB_HOST}
    #            DB_PORT: ${DB_PORT}
    #            REDIS_PASS: ${REDIS_PASS}
    #            REDIS_HOST: ${REDIS_HOST}
    #            REDIS_PORT: ${REDIS_PORT}
    #            ACCESS_SECRET: ${ACCESS_SECRET}
    #            REFRESH_SECRET: ${REFRESH_SECRET}
    restart: always