version: '3.8'
services:
  pgsync:
    network_mode: host
    build: '.'
    volumes:
      - ./dist:/dist
      - ./src:/src
      - ./config.yaml:/src/config.yaml
    command:
      - ash
      - -c
      - "sleep infinity"
    restart: always