name: Build Static Releases

on:
  release:
    types: [ created ]

jobs:
  build:
    name: Build static releases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"

      - name: Build static release
        run: |
          go build  -ldflags "-s -w" -o=dist/pg-el-sync_linux_amd64 .

      - name: Upload Release Asset
        uses: csexton/release-asset-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          pattern: "dist/*"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ steps.create_release.outputs.upload_url }}